export const ASSET_TYPE_COIN = 'COIN';
export const ASSET_TYPE_TOKEN = 'TOKEN';

export const CHAIN_LIST_MAP = {
    ALL: ['eth', 'bsc', 'polygon'],
    BSC: ['bsc'],
    ETH: ['eth'],
    POLYGON: ['polygon'],
};
export const CHAIN_ID_MAP = {
    ETH: 1,
    BSC: 56,
    POLYGON: 137,
    TRON: 999,
    ARB: 42161,
    BTTC: 199,
};
export const CHAIN_ID_TYPE_MAP = {
    1: 'ETH',
    56: 'BSC',
    137: 'POLYGON',
    999: 'TRON',
    199: 'BTTC',
    42161: 'ARB',
};
export const CHAIN_TO_SYMBOL_MAP = {
    ETH: 'ETH',
    BSC: 'BNB',
    POLYGON: 'MATIC',
    TRON: 'TRX',
    ARB: 'ARB',
    BTTC: 'BTTC',
};
export const btc = {
    order: 0,
    symbol: 'BTC',
    name: 'Bitcoin',
    id: 'bitcoin',
    chain: 'BTC',
    chainType: 'BTC',
    type: ASSET_TYPE_COIN,
    decimals: 8,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://assets.coingecko.com/coins/images/1/large/bitcoin.png',
};
export const eth = {
    order: 1,
    symbol: 'ETH',
    name: 'Ethereum',
    id: 'ethereum',
    chain: 'ETH',
    chainType: 'EVM',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://assets.coingecko.com/coins/images/279/large/ethereum.png',
};
export const bsc = {
    order: 5,
    symbol: 'BNB',
    name: 'Binance Coin',
    id: 'binancecoin',
    chain: 'BSC',
    chainType: 'EVM',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://assets.coingecko.com/coins/images/825/large/binance-coin-logo.png',
};
export const polygon = {
    order: 6,
    symbol: 'MATIC',
    name: 'Matic',
    id: 'matic-network',
    chain: 'POLYGON',
    chainType: 'EVM',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://assets.coingecko.com/coins/images/4713/large/matic-token-icon.png',
};
export const tron = {
    order: 7,
    symbol: 'TRX',
    name: 'Tron',
    id: 'tron',
    chain: 'TRON',
    chainType: 'TRON',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1958.png',
};
export const vcoin = {
    order: 4,
    symbol: 'VCOIN',
    name: 'VCoin',
    id: 'vcoin',
    chain: 'BSC',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0xbb142a12E8C390abA192EcD9E3a72f076e47Dd8d',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://epay-images.s3.us-east-2.amazonaws.com/logo.png',
};
export const bln = {
    order: 3,
    symbol: 'BLN',
    name: 'BalanceNetwork',
    id: '0x5cf8ea4278f689b301c4a17ddca9d5ec8b0b0511',
    chain: 'BSC',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x5Cf8eA4278f689B301C4a17DdCa9D5ec8b0B0511',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://s2.coinmarketcap.com/static/img/coins/64x64/21983.png',
};
export const duku_erc20 = {
    order: 2,
    symbol: 'DUKU',
    name: 'KUKU DOLLAR',
    id: 'duku',
    chain: 'ETH',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0xBf9CF55bCf5b3A6e3A5560d897D2eA17908F7D00',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://dukuwallet-2aeb92c5caa8.herokuapp.com/content/kuku_dollar.png',
};
export const duku_bep20 = {
    order: 3,
    symbol: 'DUKU',
    name: 'KUKU DOLLAR',
    id: 'duku',
    chain: 'BSC',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0xBf9CF55bCf5b3A6e3A5560d897D2eA17908F7D00',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://dukuwallet-2aeb92c5caa8.herokuapp.com/content/kuku_dollar.png',
};
export const duku_tron = {
    order: 4,
    symbol: 'DUKU',
    name: 'KukuDollar',
    id: 'duku',
    chain: 'TRON',
    chainType: 'TRON',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: 'TXNgeo4AM9vn87GFSFu3tHGxvT46N39nLn',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://dukuwallet-2aeb92c5caa8.herokuapp.com/content/kuku_dollar.png',
};
export const kuku_bep20 = {
    order: 4,
    symbol: 'KUKU',
    name: 'panKuKu',
    id: 'pankuku',
    chain: 'BSC',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x84Fd7CC4Cd689fC021eE3D00759B6D255269D538',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://dukuwallet-2aeb92c5caa8.herokuapp.com/content/kuku.jpg',
};
export const world_bep20 = {
    order: 4,
    symbol: 'WORLD',
    name: 'KUKU World',
    id: 'worldkuku',
    chain: 'BSC',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x0293cd84D7C67D508DeA8d8Dd28a9C4E8bd1b8Fa',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://dukuwallet-2aeb92c5caa8.herokuapp.com/content/worldkuku.jpg',
};
export const world_erc20 = {
    order: 4,
    symbol: 'WORLD',
    name: 'KUKU World',
    id: 'worldkuku',
    chain: 'ETH',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x0293cd84D7C67D508DeA8d8Dd28a9C4E8bd1b8Fa',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://dukuwallet-2aeb92c5caa8.herokuapp.com/content/worldkuku.jpg',
};
